# Generated by Django 5.0.4 on 2024-04-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmedico',
            name='crm',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
